version: '3.8'
include:
  - proxy.yaml

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    depends_on:
      - "db"
    ports:
      - "80:80"
    restart: always
    env_file:
    - ./.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
        backend:
          ipv4_address: 172.20.0.5

  db:
    image: mysql:8
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./db_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          memory: 256M
    env_file:
    - ./.env
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%"
    networks:
        backend:
          ipv4_address: 172.20.0.10

networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24